#数据源配置
spring:
  datasource:
    username: root
    url: jdbc:mysql://47.100.210.244:3306/VEStation
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1602liuqijun
    type: com.alibaba.druid.pool.DruidDataSource